#!/bin/sh
#
# init.d script to start up healthcare nodeJs application
#
# Copyright (c) 2014 Next Century
#
# This is free software; you may redistribute it and/or modify
# it under the terms provided by Next Century Inc.
#
# This is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the terms of Next Century terms if
# not, contact Next Century Inc., 7075 Samuel Morse Dr. Suite 210
# Columbia, MD 02146 USA
#
### BEGIN INIT INFO
# Provides:          forever
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tomcat instance supporting owf
# Description:       Starts the nodejs with the HealthcareDemoApp.js
### END INIT INFO

PORT=8082
DB_HOST=127.0.0.1
JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/"
PATH="$PATH:$JAVA_HOME/bin"
BUILD_ID=dontKillNode
#DEPLOYMENT_DIRECTORY="/deploy/healthcare-demo"
DEPLOYMENT_DIRECTORY="/home/demoadmin/healthcare-demo"

DAEMON=/usr/bin/nodejs
DESC=HealthCare-Demo

# Default defaults.  Can be overridden by the /etc/default/$NAME
NAME=forever
RUNDIR=/home/demoadmin/healthcare-demo
# if deployment directory exist, use it, else use directory of user
if [ -d "$DEPLOYMENT_DIRECTORY" ]; then
    RUNDIR=$DEPLOYMENT_DIRECTORY
fi

PIDFILE=$RUNDIR/$NAME.pid
LOGFILE=/var/log/$NAME/$NAME.log

if test ! -x $DAEMON; then
    echo "Could not find $DAEMON"
    exit 0
fi


. /lib/lsb/init-functions

cd $RUNDIR
echo "run dir : " $RUNDIR

TARTTIME=2
DIETIME=2                   # Time to wait for the process to die, in seconds
                            # If this value is set too low you might not
                            # let some servers to die gracefully and
                            # 'restart' will not work

DAEMONUSER=${DAEMONUSER:-demoadmin}
DAEMON_APPS_JS=${DAEMON_OPTS:-$RUNDIR"/healthcareDemoApp.js"}
DAEMON_START_OPTS=${DAEMON_OPTS:-"start "$RUNDIR"/healthcareDemoApp.js"}
DAEMON_STOP_OPTS=${DAEMON_OPTS:-"stop healthcareDemoApp.js || true"}
START="/usr/local/bin/"$NAME

# no idea what this does, modeled after the mongodb script
set -e


running_pid() {
# Check if a given process pid's cmdline matches a given name
    pid=$1
    name=$2
    #if pid null or emptym return 1
    [ -z "$pid" ] && return 1
    # if directory exist, return 1
    [ -d /proc/$pid ] &&  return 1
    # determine the name of the process for a given pid
    cmd1=`ps -eaf | grep $pid| grep $NAME -c`
    # Is this the expected pid
    [ "$cmd1" != "0" ] &&  return 1
    return 0
}

running() {
# Check if the process is running looking at /proc
# (works for all users)

    # No pidfile, probably no daemon present
    [ ! -f "$PIDFILE" ] && return 1
    pid=`cat $PIDFILE`
    running_pid $pid $DAEMON && return 1
    return 0
}

start_process() {
    start-stop-daemon --background --start --quiet --pidfile $PIDFILE \
                      --make-pidfile --chuid $DAEMONUSER \
                      --exec $START -- $DAEMON_START_OPTS >>$LOGFILE 2>&1 &
    errcode=$?
    # give service some time to startup
    [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
    # get the pid of the tomcat process that started up
    cmd=`ps -eaf | grep $DAEMON_APPS_JS | grep -v grep | cut -c10-15`
    # trim the value
    cmd= echo $cmd |tr -d ' '
    # have to update the pid in the pidfile
    echo $cmd > $PIDFILE &
    return $errcode
}

stop_process() {
    # Stop the process using the pid
    # Consider getting the shutdown script to work for a graceful shutdown
    start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                      --chuid $DAEMONUSER
    errcode=$?
    return $errcode
}

force_stop() {
# Force the process to die killing it manually
	[ ! -e "$PIDFILE" ] && return
	if running ; then
		kill -15 $pid
	# Is it really dead?
		sleep "$DIETIME"s
		if running ; then
			kill -9 $pid
			sleep "$DIETIME"s
			if running ; then
				echo "Cannot kill $NAME (pid=$pid)!"
				exit 1
			fi
		fi
	fi
	rm -f $PIDFILE
}


case "$1" in
  start)
        # Check if it's running first
        if running ;  then
            log_daemon_msg "apparently already running"
            log_progress_msg "apparently already running"
            log_end_msg 0
            exit 0
        fi
        if start_process ; then
            # NOTE: Some servers might die some time after they start,
            # this code will detect this issue if STARTTIME is set
            # to a reasonable value
            [ -n "$STARTTIME" ] && sleep $STARTTIME # Wait some time
            if  running ;  then
                # It's ok, the server started and is running
                log_end_msg 0
            else
                # It is not running after we did start
                log_end_msg 1
            fi
        else
            # Either we could not start it
            log_end_msg 1
        fi
	;;
  stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        if running ; then
            # Only stop the server if we see it running
			errcode=0
            stop_process || errcode=$?
            log_end_msg $errcode
        else
            # If it's not running don't do anything
            log_progress_msg "apparently not running"
            log_end_msg 0
            exit 0
        fi
        ;;
  force-stop)
        # First try to stop gracefully the program
        $0 stop
        if running; then
            # If it's still running try to kill it more forcefully
            log_daemon_msg "Stopping (force) $DESC" "$NAME"
			errcode=0
            force_stop || errcode=$?
            log_end_msg $errcode
        fi
	;;
  restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
		errcode=0
        stop_process || errcode=$?
        # Wait some sensible amount, some server need this
        [ -n "$DIETIME" ] && sleep $DIETIME
        start_process || errcode=$?
        [ -n "$STARTTIME" ] && sleep $STARTTIME
        running || errcode=$?
        log_end_msg $errcode
	;;
  status)

        if running ;  then
            log_daemon_msg "apparently already running"
            log_progress_msg "running"
            log_end_msg 0
        else
            log_daemon_msg "apparently not running"
            log_progress_msg "apparently not running"
            log_end_msg 1
            exit 1
        fi
        ;;
  # MongoDB can't reload its configuration.
  reload)
        log_warning_msg "Reloading $NAME daemon: not implemented, as the daemon"
        log_warning_msg "cannot re-read the config file (use restart)."
        ;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
